config/routes.rb
Rails.application.routes.draw do
  resources :prospects do
    post "disposition"
    collection { post :import }
    resources :results, only: [:create, :edit, :update, :destroy]
  end
  
  devise_for :users
  root 'prospects#menu' 
  get "menu" => "prospects#menu"
  get "update_accessible" => "results#update_accessible"
  get 'edit_contacts/:id' => 'prospects#edit_contacts', as: :edit_contacts
end

app/views/shared/_footer.html.erb
<div id="footer">
  <nav class="navbar navbar-inverse navbar-fixed-bottom">
    <div class="container">
      <p align="center" style="color:white;"><a href="http://gosell.co">GoSell &copy; 2016</a>
        &nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;
        <a href="http://gosell.co/support">Contact Support</a>
        <%= " - - (Viewing in Development)" if Rails.env.development? %></p>
    </div>
  </nav>
</div>

app/views/shared/_head.html.erb
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => false %>
    
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{ENV['GOOGLE_API_KEY']}" %>
    <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" %>
    <%= csrf_meta_tags %>
    <%= render "shared/shim" %>
  </head>

app/views/shared/_leaderboard.html.erb
    <div class="panel panel-default col-md-6 pull-right" id="panel-container">
      <div class="panel-heading">
        <h2 class="panel-title">Activity Leaderboard</h2>
      </div>
        
      <div class="container-fluid">
        
        <div class="row">
          <div class="col-xs-12">        
            <ul class="nav nav-tabs">
              <li role="presentation" class="active"><a href="#">Today</a></li>
              <li role="presentation"><a href="#">This Week</a></li>
              <li role="presentation"><a href="#">Last 30 Days</a></li>
            </ul>
          </div>
        </div>
        
        
        
        <div class="row">
          <div class="col-xs-6">
            User:  <%= current_user.first_name %> <%= current_user.last_name %>
          </div>
          <div class="col-xs-6">
            Signed in: <%= current_user.current_sign_in_at.strftime("%m/%d/%y at %I:%M %p") %>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-6">
            Username: <%= current_user.username %>
          </div>
          <div class="col-xs-6">
            Last Sign in: <%= current_user.last_sign_in_at.strftime("%m/%d/%y at %I:%M %p") %>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-6">
            User Signed up on: <%= current_user.created_at.strftime("%m/%d/%y") %>
          </div>
          <div class="col-xs-6">
            User Sign-ins: <%= current_user.sign_in_count %>
          </div>
        </div>

        <div class="row">
          <div class="col-xs-6">
            Record dispositions <%= @prospect.results.count %>
          </div>
          <div class="col-xs-6">
            Last disposition: <%= @prospect.results.last.disposition %>
          </div>
        </div>

        <div class="row">
          <div class="col-xs-12">
            Activity Leaderboard will be here - This is temporary placeholder data.
          </div>
        </div>
      </div>

        <div class="panel-footer">
          Footer
        </div>
      </div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container-fluid">
    <%= link_to image_tag("logo-black-white.png", alt: "GoSell Logo"), "#", class: "navbar-brand", id: "logo" %>
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>


        

          <li><%= link_to raw("<i class=\"fa fa-home\"></i> Main Menu"), menu_path , method: :get %></li>
          <li><%= link_to raw("<i class=\"fa fa-gear\"></i> User Settings"), edit_user_registration_path, method: :get %></li>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
          <% end %>
          <% if !user_signed_in? %>
          <li><%= link_to 'Log in', new_user_session_path, method: :get %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_shim.html.erb
<!--[if lt IE 9]
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->