config/routes.rb
Rails.application.routes.draw do
  resources :prospects do
    post "disposition"
    collection { post :import }
    resources :results, only: [:create, :edit, :update, :destroy]
  end
  
  devise_for :users
  root 'prospects#menu' 
  get "menu" => "prospects#menu"
  get "update_accessible" => "results#update_accessible"
  get 'edit_contacts/:id' => 'prospects#edit_contacts', as: :edit_contacts
end

app/models/prospect.rb
class Prospect < ApplicationRecord
  belongs_to :user, required: true
  has_many :notes
  accepts_nested_attributes_for :notes, allow_destroy: true
  has_many :results
  accepts_nested_attributes_for :results, allow_destroy: true
  validates :company, presence: true

# the following 7 lines for searching by company name
  def self.search(co)
    if co
      where('company LIKE ?', "%#{co}%")
    else
      all
    end
  end

# the following 7 lines for searching by street name
  def self.lookup(loc)
    if loc
      where('address LIKE ?', "%#{loc}%")
    else
      all
    end
  end

# the following 8 lines for exporting to csv
  def self.to_csv(fields = column_names, options = {})
    CSV.generate(options) do |csv|
      csv << fields
      all.each do |prospect|
        csv << prospect.attributes.values_at(*fields)
      end
    end
  end

# the following 7 lines for importing from csv
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      prospect_hash = row.to_hash
      prospect = find_or_create_by!(user_id: prospect_hash['user_id'], campaign: prospect_hash['campaign'], list_number: prospect_hash['list_number'], source: prospect_hash['source'], company_phone: prospect_hash['company_phone'], company: prospect_hash['company'], first_name: prospect_hash['first_name'], last_name: prospect_hash['last_name'], title: prospect_hash['title'], address: prospect_hash['address'], address2: prospect_hash['address2'], city: prospect_hash['city'], state: prospect_hash['state'], zip: prospect_hash['zip'], county: prospect_hash['county'], fax: prospect_hash['fax'], numberofemployees: prospect_hash['numberofemployees'], website: prospect_hash['website'], sic: prospect_hash['sic'])
      prospect.update_attributes(prospect_hash)
    end
  end
end

app/controllers/prospects_controller.rb
class ProspectsController < ApplicationController
  before_action :set_prospect, only: [:show, :edit, :edit_contacts, :update, :destroy]
  skip_before_action :verify_authenticity_token
  before_filter :authenticate_user!, :except => [:home]

  def index
    # Following 1 line for kalinari pagination - below lines using as a method
    @prospects = Prospect.order("id").page(params[:page]).per(5)
    
    # Following 3 lines for serching by street name
    if params[:loc] != nil
      @prospects = Prospect.lookup(params[:loc]).page(params[:page]).per(5) 
    end 

    # Following 3 lines for serching by company name
    if params[:co] != nil
      @prospects = Prospect.search(params[:co]).page(params[:page]).per(5)
    end
 
    # Following 4 lines selecting by list number
    if params[:list_number] != nil
      @prospects = Prospect.where(list_number: params[:list_number]).page(params[:page]).per(5)
      @goList = Prospect.select(:list_number).order(:list_number).distinct
    end

    # Following 4 lines are for CSV export 
    respond_to do |format|
      format.html
      format.csv { send_data @prospects.to_csv(['user_id', 'campaign', 'list_number', 'source', 'company_phone', 'company', 'first_name', 'last_name', 'title', 'address', 'address2', 'city', 'state', 'zip', 'county', 'fax', 'numberofemployees', 'website', 'sic']) }
    end

  end

  # Following 4 lines for importing from csv
  def import
    Prospect.import(params[:file])
    redirect_to root_url, notice: "Prospects imported."
  end

  # Allowing for nested form to create results and notes
  def show
    @result = Result.new
    @note = Note.new
  end
  
  def new
    @prospect = Prospect.new
  end

  def create
    @prospect = Prospect.new(prospect_params)
    respond_to do |format|
      if @prospect.save
        format.html { redirect_to @prospect, notice: 'New Prospect was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end  

  def edit
  end

  def update
    respond_to do |format|
      if @prospect.update(prospect_params)
        format.html { redirect_to @prospect, notice: 'Prospect was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @prospect.destroy
    respond_to do |format|
      format.html { redirect_to prospects_url, notice: 'Prospect was successfully deleted.' }
    end
  end

end


private
  def set_prospect
    @prospect = Prospect.find(params[:id])
  end
    
  def prospect_params
    params
        .require(:prospect)
        .permit(:campaign, :list_number, :time_on_contact, :status, :source,
                :company, :company_phone, :address, :address2, :city, :state,
                :zip, :county, :fax, :website, :numberofemployees, :first_name,
                :last_name, :title, :phone, :m_phone, :email, :alt_email,
                :linkedin, :facebook, :born_on, :first_name_2, :last_name_2,
                :title_2, :phone_2, :m_phone_2, :email_2, :alt_email_2,
                :linkedin_2, :facebook_2, :born_on_2, :first_name_3,
                :last_name_3, :title_3, :phone_3, :m_phone_3, :email_3,
                :alt_email_3, :linkedin_3, :facebook_3, :born_on_3, :other1,
                :other2, :other3, :other4, :other5, :other6, :other7, :other8,
                :eventdatetime, :sic, :primary_contact, :canvassed, :called, :user_id,
                notes_attributes: [:detail],
                results_attributes: [:id, :disposition, :event, :activity,
                :coordinates, :latitude, :longitude,:location, :user_id])
  end

app/helpers/prospects_helper.rb
module ProspectsHelper
end

app/views/prospects/edit.html.erb
<%= render 'edit_prospect_form', prospect: @prospect %>

app/views/prospects/edit_contacts.html.erb
<%= render 'contact_form', prospect: @prospect %>

app/views/prospects/index.html.erb
<% provide(:title, "Making Sales a Competitive Sport") %>

<div id="agent-view">
  <div class="container-fluid">
    <div class="panel panel-default col-md-6" id="panel-container">
      <div class="panel-heading">
        <div class="row">
          <div class="col-md-12 right">
            <%= form_tag import_prospects_path, multipart: true, class: 'form-inline' do %>
              <div class="form-group">
                <%= submit_tag "Import CSV", class: 'btn btn-info gradient round raised btn-xs' %>
              </div>
              <div class="form-group">
                <%= file_field_tag :file %>
              </div>
              <div class="form-group">
                <%= link_to "Export CSV", prospects_path(format: "csv"), class: 'btn btn-primary gradient round raised btn-xs' %>
              </div>
            <% end %>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <strong>Listing Prospects</strong>
          </div>
        </div>
      </div>
      <div class="container-fluid">
        <div class="col-xs-12">
          <br>
          <table border="1" width="100%">
            <tr background="black">
              <th>UserID</th><th>Campaign</th><th>List#</th><th>Company</th>
              <!--<th>Co Phone</th><th>City</th><th>State</th><th>Full Name</th><th>Title</th>-->
              <th colspan="3">Show/ Edit / Delete</th>
            </tr>
            
            <% @prospects.each do |p| %>
            <tr>
              <td><%= p.user_id %></td><td><%= p.campaign %></td><td><%= p.list_number %></td><td><%= p.company %></td>

              <!--<td><%= p.company_phone %></td><td><%= p.city %></td><td><%= p.state %></td><td><%= p.first_name %> <%= p.last_name %></td><td><%= p.title %></td>-->

              <td><%= link_to 'Show', p, class: "btn btn-default btn-xs" %></td>
              <td><%= link_to "Edit", edit_prospect_path(p), class: "btn btn-warning btn-xs" %></td>
              <td><%= link_to "Delete", p, method: :delete, data: { confirm: 'Are you sure?'}, class: "btn btn-danger btn-xs" %></td>
            </tr>
            <% end %>
          </table>
        </div>
        
        <div class="row center">
          <%= paginate @prospects %>
        </div>
        
      </div>
      
      <div class="panel-footer">
        <div class="btn-toolbar">
          <%= link_to 'New Prospect', new_prospect_path, class: "btn btn-primary gradient round raised btn-block" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/prospects/menu.html.erb
<% provide(:title, "Making Sales a Competitive Sport") %>

<div id="agent-view">
  <div class="container-fluid">
    <div class="panel panel-default col-md-6" id="panel-container">
      <div class="panel-heading">
        <h2 class="panel-title center">Menu</h2>
      </div>
      <div class="container-fluid">
        <div class="row">&nbsp;</div>
        
        <div class="row">
          <div class="col-xs-12 center">
            <div class="btn-group">
              <button type="button" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span class="fa fa-list"></span> Select Action<span class="caret"></span>
              </button>
              <ul class="dropdown-menu dropdown-menu-right">
                  <li><a data-target="#smileDial" data-toggle="collapse" data-parent="#menuGroup">Smile & Dial</a></li>
                  <li><a data-target="#walkTalk" data-toggle="collapse" data-parent="#menuGroup">Walk & Talk</a></li>
                  <li><a data-target="#followup" data-toggle="collapse" data-parent="#menuGroup">Follow-up</a></li>
                  <li><a data-target="#appointments" data-toggle="collapse" data-parent="#menuGroup">Appointments</a></li>
                  <li><a data-target="#search" data-toggle="collapse" data-parent="#menuGroup">Search for Lead(s)</a></li>
                  <li><%= link_to "List All Leads", prospects_path %></li>
                  <li><%= link_to "Add Lead(s)", new_prospect_path %></li>
              </ul>
            </div>
          </div>
        </div>
      
        <div class="accordion-group">
          <div id="smileDial" class="collapse">
            <div class="row">
              <div class="col-xs-12 center">&nbsp;<br>&nbsp;</div>
            </div>
            <div class="col-xs-12 center">Smile & Dial:
              <div class="btn-group">
                <button type="button" class="btn btn-default btn-sm dropdown-toggle"
                  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <span class="fa fa-list"></span> Select List 
                  <span class="caret"></span>
                </button>
                <ul class="dropdown-menu dropdown-menu-right">
                  <% @goList.each do |p| %>
                    <li><%= link_to "#{p.list_number}", prospects_path(list_number: p.list_number) %></li>
                  <% end %>
                </ul>
              </div>
            </div>
          </div>
          
  
          <div id="walkTalk" class="collapse">
            <div class="row">
              <div class="col-xs-12 center">&nbsp;<br>&nbsp;</div>
            </div>
            <div class="row">
              <div class="col-xs-10 right">
                <%= form_tag(prospects_path, method: :get) do %>
                Walk & Talk: <%= text_field_tag :loc, params[:loc], placeholder: "Search by Street" %>
                  <%= submit_tag 'Go', class:"btn btn-info gradient round raised btn-xs", name: nil %>
                <% end %>
              </div>
              <div class="col-xs-2">
              </div>
            </div>
          </div>
          
          
          <div id="search" class="collapse">
            <div class="row">
              <div class="col-xs-12 center">&nbsp;<br>&nbsp;</div>
            </div>
            <div class="row">
              <div class="col-xs-10 center">
                <%= form_tag(prospects_path, method: :get) do %>
                  Search for a Prospect: <%= text_field_tag :co, params[:co], placeholder: "Search by Company" %>
                  <%= submit_tag 'Go', class:"btn btn-info gradient round raised btn-xs", name: nil %>
                <% end %>
              </div>
              <div class="col-xs-2">
              </div>
            </div>
          </div>
        
        </div>
      

        
        
<div class="panel-group" id="accordion">
  <div class="panel panel-default">
    <div class="panel-heading center">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapse1">
        Smile & Dial</a>
      </h4>
    </div>
    <div id="collapse1" class="panel-collapse collapse">
      <div class="panel-body">
            <div class="row">
              <div class="center">&nbsp;</div>
            </div>
            <div class="row center">
              <div class="btn-group">
                <button type="button" class="btn btn-default btn-sm dropdown-toggle"
                  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <span class="fa fa-list"></span> Select List 
                  <span class="caret"></span>
                </button>
                <ul class="dropdown-menu dropdown-menu-right">
                  <% @goList.each do |p| %>
                    <li><%= link_to "#{p.list_number}", prospects_path(list_number: p.list_number) %></li>
                  <% end %>
                </ul>
              </div>
            </div>
            <div class="row">
              <div class="center">&nbsp;</div>
            </div>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading center">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapse2">
        Walk & Talk</a>
      </h4>
    </div>
    <div id="collapse2" class="panel-collapse collapse">
      <div class="panel-body">
      
        <div class="row">
          <div class="center">&nbsp;</div>
        </div>
        <div class="row">
          <div class="center">
            <%= form_tag(prospects_path, method: :get) do %>
            Walk & Talk: <%= text_field_tag :loc, params[:loc], placeholder: "Search by Street" %>
              <%= submit_tag 'Go', class:"btn btn-info gradient round raised btn-xs", name: nil %>
            <% end %>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-12 center">&nbsp;</div>
        </div>     
      
      </div>
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading center">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapse3">
        Search</a>
      </h4>
    </div>
    <div id="collapse3" class="panel-collapse collapse">
      <div class="panel-body">
      
        <div class="row">
          <div class="center">&nbsp;</div>
        </div>
        <div class="row">
          <div class="center">
            <%= form_tag(prospects_path, method: :get) do %>
              Search for a Prospect: <%= text_field_tag :co, params[:co], placeholder: "Search by Company" %>
              <%= submit_tag 'Go', class:"btn btn-info gradient round raised btn-xs", name: nil %>
            <% end %>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-12 center">&nbsp;</div>
        </div>     
      
      </div>
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading center">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapse4">
        Somthing Else</a>
      </h4>
    </div>
    <div id="collapse4" class="panel-collapse collapse">
      <div class="panel-body">
      
        <div class="row">
          <div class="center">&nbsp;</div>
        </div>
        <div class="row">
          <div class="center">
            <%= form_tag(prospects_path, method: :get) do %>
            Walk & Talk: <%= text_field_tag :loc, params[:loc], placeholder: "Search by Street" %>
              <%= submit_tag 'Go', class:"btn btn-info gradient round raised btn-xs", name: nil %>
            <% end %>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-12 center">&nbsp;</div>
        </div>     
      
      </div>
    </div>
  </div>

</div>
      
        
        

      </div>
      
    <div class="panel-footer">&nbsp;</div>
    
  </div>
</div>

app/views/prospects/new.html.erb
<% provide(:title, "Making Sales a Competitive Sport") %>

<%= form_for(@prospect) do |f| %>
  <% if @prospect.errors.any? %>
    <div id="error_explanation">
      <p class="alert alert-danger"><%= pluralize(@prospect.errors.count, "error") %> prohibited this prospect from being saved:</p>
        <% @prospect.errors.full_messages.each do |message| %>
      <p class="alert alert-danger"><em>&nbsp; * <%= message %></em></p>
      <% end %>
    </div>
  <% end %>

<div id="agent-view">
  <div class="container-fluid">
    <div class="panel panel-default col-md-6" id="panel-container">
      <div class="panel-heading">
        <h2 class="panel-title">Add New Prospect</h2>
      </div>
      
      <div class="container-fluid">
        
        <div class="cant-see-me">
          <%= f.hidden_field :user_id, value: current_user.id %>
        </div>

        <div class="row center" style="background: gold;">
          <div class="form-group col-xs-12 center" style="background: gold;">
            Use your phone's camera to Scan Business Card <i class="fa fa-camera"></i>
          </div>
          <div class="col-xs-12" style="background: gold;">
            <input type="file" accept="image/*" capture="camera">
          </div>
        </div>
        
        <div class="row">
          <div class="form-group col-xs-6">
            <%= f.label :campaign %>
            <%= f.text_field :campaign, class: "form-control" %>
          </div>
          <div class="form-group col-xs-6">
            <%= f.label :list_number %>
            <%= f.text_field :list_number, class: "form-control" %>
          </div>
        </div>
        
        <div class="row">
          <div class="form-group col-xs-6">
            <%= f.label :company %>
            <%= f.text_field :company, class: "form-control" %>
          </div>
        </div>

        <div class="row">
          <div class="form-group col-xs-4">
            <%= f.label :first_name %>
            <%= f.text_field :first_name, class: "form-control" %>
          </div>
          <div class="form-group col-xs-4">
            <%= f.label :last_name %>
            <%= f.text_field :last_name, class: "form-control" %>
          </div>
          <div class="form-group col-xs-4">
            <%= f.label :title %>
            <%= f.text_field :title, class: "form-control" %>
          </div>
        </div>

        <div class="row">
          <div class="form-group col-xs-6">
            <%= f.label :company_phone %>
            <%= f.text_field :company_phone, class: "form-control" %>
          </div>
          <div class="form-group col-xs-6">
            <%= f.label :website %>
            <%= f.text_field :website, class: "form-control" %>
          </div>
        </div>
        <div class="row">
          <div class="form-group col-xs-6">
            <%= f.label :address %>
            <%= f.text_field :address, class: "form-control" %>
          </div>
          <div class="form-group col-xs-6">
            <%= f.label :address2 %>
            <%= f.text_field :address2, class: "form-control" %>
          </div>
        </div>
        <div class="row">
          <div class="form-group col-xs-3">
            <%= f.label :city %>
            <%= f.text_field :city, class: "form-control" %>
          </div>
          <div class="form-group col-xs-3">
            <%= f.label :state %>
            <%= f.text_field :state, class: "form-control" %>
          </div>
          <div class="form-group col-xs-3">
            <%= f.label :zip %>
            <%= f.text_field :zip, class: "form-control" %>
          </div>
          <div class="form-group col-xs-3">
            <%= f.label :county %>
            <%= f.text_field :county, class: "form-control" %>
          </div>
        </div>
      </div>
      <div class="panel-footer">
        <div class="btn-toolbar">
          <div class="col-xs-6">
          <%= link_to 'Back', prospects_path, class: "btn btn-default gradient raised btn-block" %>
          </div>
          <div class="col-xs-6">
          <%= f.submit class: "btn btn-primary gradient raised btn-block pull-right" %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/prospects/show.html.erb
<% provide(:title, "Making Sales a Competitive Sport") %>

<div id="agent-view">
  <div class="container-fluid">
    <div class="panel panel-default col-md-6" id="panel-container">
      <div class="panel-heading">
       <div class="col-xs-12"><h6 align="right">Campaign: <%= @prospect.campaign %> | List#: <%= @prospect.list_number %></h6></div>
        <h2 class="panel-title"><%= @prospect.company %></h2>
      </div>
        
      <div class="container-fluid">
        <div class="row">
          <div class="col-xs-10">
            <div class="row">
              <div class="col-xs-7">
                <% if @prospect.primary_contact == 3 %>
                    <%= @prospect.first_name_3 %> <%= @prospect.last_name_3 %>
                  <% elsif @prospect.primary_contact == 2 %>
                    <%= @prospect.first_name_2 %> <%= @prospect.last_name_2 %>
                  <% else %>
                    <%= @prospect.first_name %> <%= @prospect.last_name %>
                <% end %>
              </div>
              <div class="col-xs-4">
                <% if @prospect.primary_contact == 3 %>
                    <%= @prospect.title_3 %>
                  <% elsif @prospect.primary_contact == 2 %>
                    <%= @prospect.title_2 %>
                  <% else %>
                    <%= @prospect.title %>
                <% end %>
              </div>
            </div>
        
            <% if @prospect.company_phone.present? %>
              <div class="row">
                <div class="col-xs-6"><span class="fa fa-phone"></span> <%= @prospect.company_phone %></div>
                <div class="col-xs-6"></div>
              </div>
            <% end %>
          </div>

          <div class="col-xs-2">
            <div class="btn-group">
              <button type="button" class="btn btn-info gradient round raised btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-user"></span><span class="caret"></span>
              </button>
              <ul class="dropdown-menu dropdown-menu-right">
                <% if @prospect.first_name.present? || @prospect.last_name.present? %>
                  <li><a data-target="#contact1" data-toggle="collapse">
                  <%= @prospect.title %> - <%= @prospect.first_name %> <%= @prospect.last_name %></a></li>
                  <% else %>
                    <li><%= link_to "Add Contact (1)", edit_contacts_path(@prospect.id) %></li>
                <% end %>
                <% if @prospect.first_name_2.present? || @prospect.last_name_2.present? %>
                  <li><a data-target="#contact2" data-toggle="collapse">
                  <%= @prospect.title_2 %> - <%= @prospect.first_name_2 %> <%= @prospect.last_name_2 %></a></li>
                  <% else %>
                    <li><%= link_to "Add Contact (2)", edit_contacts_path(@prospect.id) %></li>
                <% end %>
                <% if @prospect.first_name_3.present? || @prospect.last_name_3.present? %>
                  <li><a data-target="#contact3" data-toggle="collapse">
                  <%= @prospect.title_3 %> - <%= @prospect.first_name_3 %> <%= @prospect.last_name_3 %></a></li>
                  <% else %>
                    <li><%= link_to "Add Contact (3)", edit_contacts_path(@prospect.id) %></li>
                <% end %>
                <% if @prospect.first_name.present? || @prospect.last_name.present? ||
                    @prospect.first_name_2.present? || @prospect.last_name_2.present? ||
                    @prospect.first_name_3.present? || @prospect.last_name_3.present? %>
                <li><a data-target="#contact1,#contact2,#contact3" data-toggle="collapse">All Contacts</a></li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>

        <% if @prospect.address.present? %>
        <div class="row">
          <div class="col-xs-12"><%= @prospect.address %>
            <% if @prospect.address2.present? %>
              &nbsp; &nbsp; - &nbsp; &nbsp; <%= @prospect.address2 %>
            <% end %>
          </div>
        </div>
        <% end %>
        <% if @prospect.city.present? || @prospect.state.present? %>
        <div class="row">
          <div class="col-xs-12"><%= @prospect.city %>
            <% if @prospect.state.present? %>, <%= @prospect.state %> &nbsp;<% end %>
              <%= @prospect.zip %>
          </div>
        </div>
        <% end %>
        <div class="row">
          <div class="col-xs-6">
            <% if @prospect.primary_contact == 3 && @prospect.email_3.present? %>
                <a href="mailto:<%= @prospect.email_3 %>">
                <span class="glyphicon glyphicon-envelope"></span> <%= @prospect.email_3 %></a>
              <% elsif @prospect.primary_contact == 2 && @prospect.email_2.present? %>
                <a href="mailto:<%= @prospect.email_2 %>">
                <span class="glyphicon glyphicon-envelope"></span> <%= @prospect.email_2 %></a>
              <% elsif @prospect.email.present? %>
                <a href="mailto:<%= @prospect.email %>">
                <span class="glyphicon glyphicon-envelope"></span> <%= @prospect.email %></a>
            <% end %>
          </div>
          <div class="col-xs-6">
            <% if @prospect.website.present? %>
              <a href="http://<%= @prospect.website %>" target="New">
              <span class="glyphicon glyphicon-globe"></span> <%= @prospect.website %></a>
            <% end %>
          </div>
        </div>

        <% @prospect.notes.each do |n| %>
          <% if n.detail.present? %>
            <div class="row">
              <div class="col-xs-12">
                Note: <%= n.created_at.strftime("%m/%d/%y") %> - <%= n.detail %>
              </div>
            </div>
          <% end %>
        <% end %>

        <% if @prospect.results.present? %>
          <% if @prospect.results.last.disposition == "appointment" %>
            <div class="row">
              <div class="col-xs-12 text-center"><strong>Appointment</strong> scheduled for 
                <%# if @prospect.results.event.present? %>
                  <strong><%#= @prospect.results.last.event.strftime("%m/%d/%y at %I:%M %p") %></strong>
                <%# end %>
              </div>
            </div>
          <% end %>
          <% if @prospect.results.last.disposition == "follow-up" %>
            <div class="row">
              <div class="col-xs-12 text-center">Must <strong>Follow up </strong> on 
                <%# if @prospect.results.event.present? %>
                  <strong><%#= @prospect.results.last.event.strftime("%m/%d/%y at %I:%M %p") %></strong>
                <%# else %>
                  <em>Date not entered!</em>
                <%# end %>    
              </div>
            </div>
          <% end %>
        <% end %>

        <%= render 'prospects/show_contacts' %>

        <%= render 'prospects/show_more' %>
      
        <%= render "results_form" %>

        <div id="default-toolbar" class="collapse in">
          <div class="row">
            <div class="col-xs-12">
              <a href="#more" class="btn btn-info btn-sm gradient raised round" role="button" data-toggle="collapse">More</a>
              <%= link_to "Edit", edit_prospect_path(@prospect), class: "btn btn-warning btn-sm gradient raised round" %>   
              <%= link_to "Delete", @prospect, method: :delete, data: { confirm: 'Are you sure you want to delete Prospect?'}, class: "btn btn-danger btn-sm gradient raised round" %>
              <a data-target="#result-form,#result-toolbar,#default-toolbar" class="btn btn-primary gradient raised round pull-right" role="button" data-toggle="collapse"><span class="fa fa-legal" aria-hidden="true"> Result</a>
            </div>
          </div>
        </div>
      </div>
    </div>

    <%= render 'shared/leaderboard' %>
      
  </div>
</div>